### ISSUE TITLE
Bug in Trip Summary

### ISSUE THREAD

**Issue by RivetR1T** [my-rivian/my-rivian#21]
I do _not_ have 'metric' enabled in Settings > General. And yet, the summary when a trip ends is displayed in kilometers. (screenshot uploaded)
![Screenshot 2024-02-19 at 4 23 08 PM 2](https://github.com/my-rivian/my-rivian/assets/156267049/6eb329aa-6230-44e9-8501-bc9802e7f293)

**Comment by my-rivian** [comment]
Thanks, noticed this Live Activity bug the other day and is fixed in the next update.
